apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config-azure
  annotations:
    meta.crossplane.io/maintainer: craig@upbound.io
    meta.crossplane.io/source: github.com/cwilhit/my-own-api
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Converting my Upbound root configuration into one for Azure
    meta.crossplane.io/readme: |
      This configuration wraps platform-ref-azure
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - configuration: xpkg.upbound.io/bricks/platform
      version: ">=v0.1.0"
